### ISSUE TITLE
Question about Learning Resources for JAX-RS Project

### ISSUE THREAD

**Issue by iRayans** [mkoutra/bookshelf-jaxrs#1]
Hi @mkoutra,

I’m currently learning JAX-RS and came across your `bookshelf-jaxrs` project, which looks like a great example to follow. I was wondering if you followed any specific tutorial or resource to build this project. I've been searching for updated resources, but many of the tutorials I find are a bit outdated.

If you have any recommendations or could point me to resources that helped you, I would really appreciate it!

Thanks for sharing this project and any guidance you can offer.

**Comment by mkoutra** [comment]
Hi @iiRyan,

Thanks for checking out my `bookshelf-jaxrs` project! I’m glad you found it useful as a reference. I’m currently in a coding bootcamp, and part of our learning process involves building projects like this to get hands-on experience with frameworks like JAX-RS.

Our instructors provided us with notes that helped in understanding and building this project. Unfortunately, I can’t share those specific materials, but I also found the [Jakarta RESTful Web Services Specification 3.1](https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.pdf) to be a great resource. It offers comprehensive explanations that might be helpful for anyone diving deeper into JAX-RS.

Feel free to reach out if you’d like to discuss or have any questions about the project!

Best,
@mkoutra

**Comment by iRayans** [comment]
Hi @mkoutra,

Thanks for sharing the resource! I appreciate it.

It sounds like your coding bootcamp offers fantastic hands-on learning. Is it a private bootcamp, or is it open for public registration? I’d like to look into it and see if it’s something I could join as well.

Thanks again,

Best,
@iiRyan

**Comment by mkoutra** [comment]
Hi @iiRyan,

Thanks for the interest! The coding bootcamp is actually run by a university in Athens and is conducted in Greek, so it might not be ideal for non-Greek speakers.

Best,
Michalis
